name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
  schedule:
    - cron: '0 15 * * 5'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '4.0'
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64 # v1.299.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Create kind cluster
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0
      - name: Run tests
        run: KUBECONFIG="$HOME/.kube/config" bundle exec rake spec

  build:
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64 # v1.299.0
        with:
          ruby-version: ruby
      - uses: release-gems/action/build@d437156fdb56ff38941834e0e8f86ea0b1f34751 # v1.1.0
        with:
          sandbox: true

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    environment: rubygems.org
    runs-on: ubuntu-slim
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: release-gems/action@d437156fdb56ff38941834e0e8f86ea0b1f34751 # v1.1.0
